Make NumPy available:

In [127]:
import numpy as np

## Exercise 07.1 (indexing and timing)

Create two very long NumPy 1D-arrays (vectors) `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for arrays of different lengths (use a very long array for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [128]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


#### (1) Add two arrays using built-in addition operator:

In [129]:
x = np.arange(0,10)
y = np.linspace(0,-9, 10)

%time y+x

CPU times: user 48 μs, sys: 79 μs, total: 127 μs
Wall time: 304 μs


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### (2) Add two arrays using own implementation:

In [130]:

def addArrays(x,y):
    if len(x)==len(y):
        added = np.zeros(len(x))
        
        for i in range(len(x)):
            added[i]=x[i]+y[i]
        
        return added
    
    else:
        print("Arrays of different lengths. Cannot add")
        exit()
    
%time addArrays(x,y)

CPU times: user 48 μs, sys: 186 μs, total: 234 μs
Wall time: 650 μs


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Optional extension: just-in-time (JIT) compilation

You will see a large difference in the time required between your NumPy and 'plain' Python implementations. This is due to Python being an *interpreted* language as opposed to a *compiled* language. A way to speed up plain Python implementions is to convert the interpreted Python code into compiled code. A tool for doing this is [Numba](https://numba.pydata.org/).

Below is an example using Numba and JIT to accelerate a computation:

In [131]:
#!pip -q install numba 
import numba
import math

def compute_sine_native(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z

@numba.jit
def compute_sine_jit(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z
    
x = np.ones(10000000)
%time z = compute_sine_native(x)
compute_sine_jit(x)
%time z = compute_sine_jit(x)

ImportError: Numba needs NumPy 2.0 or less. Got NumPy 2.1.

**Task:** Test if Numba can be used to accelerate your implementation that uses indexing to sum two arrays, and by how much.

In [ ]:
...

## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [65]:
def to_percentage_and_sort(scores):
    percentages = np.array([(10*i)/6 for i in scores])
    
    percentages.sort()
    
    return percentages

def statistics(scores, exclude=False):
    scores.sort()
    
    if exclude == True:
        scores = scores[1:-1]
    
    return {'min': scores.min(), 
            'max' : scores.max(),
            'mean' : scores.mean()}

print(to_percentage_and_sort(scores))

[13.         40.         58.33333333 70.         96.66666667]


In [66]:
## tests ##

scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert np.isclose(s0["min"], 7.8)
assert np.isclose(s0["mean"], 33.36)
assert np.isclose(s0["max"], 58.0)

s1 = statistics(scores, True)
assert np.isclose(s1["min"], 24.0)
assert np.isclose(s1["mean"], 33.666666666666666667)
assert np.isclose(s1["max"], 42.0)

## Exercise 07.3 (slicing)

For the two-dimensional array

In [68]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.

**Check your results carefully against hand computations.**

#### 1. Extract the third column as a 1D array

In [92]:
n=3 #column no.

A[:,n-1]

array([  -2.43,   54.7 ,    3.64, -113.2 ])

#### 2. Extract the first two rows as a 2D sub-array

In [96]:
n = 2 #number of rows

A[:n,:]


array([[ 4.  ,  7.  , -2.43, 67.1 ],
       [-4.  , 64.  , 54.7 , -3.33]])

#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [105]:
n = 2 # size of bottom right square block to be extracted

A[-n:,-n:]


array([[   3.64,    4.11],
       [-113.2 ,  323.22]])

#### 4. Sum the last column

In [107]:
n = 4 #column to sum

sum(A[:,n-1])

np.float64(391.1)

#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [113]:
rows, columns = np.shape(A)[1], np.shape(A)[0]
B = np.zeros((rows, columns))

for i in range(len(A)):
    B[i,:] = A[:,i]

B, A

(array([[   4.  ,   -4.  ,    2.43,    1.2 ],
        [   7.  ,   64.  ,   23.2 ,    2.5 ],
        [  -2.43,   54.7 ,    3.64, -113.2 ],
        [  67.1 ,   -3.33,    4.11,  323.22]]),
 array([[   4.  ,    7.  ,   -2.43,   67.1 ],
        [  -4.  ,   64.  ,   54.7 ,   -3.33],
        [   2.43,   23.2 ,    3.64,    4.11],
        [   1.2 ,    2.5 , -113.2 ,  323.22]]))

## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [134]:
from scipy import optimize

def my_f(x):
    """Evaluate polynomial function"""
    return x**5 / 10 + x**3 - 10 * x**2 + 4 * x + 7

def compute_root(f, x0, x1, tol, max_it):
    # Iterate until tolerance is met
    it = 0
    error = tol + 1.0
    while error > tol:
        # Compute midpoint
        x_mid = (x0 + x1) / 2

        # Evaluate function at (i) left end-point and at (ii) midpoint
        f0 = f(x0)
        f_mid = f(x_mid)

        if f0*f_mid < 0:
            x1 = x_mid
        else:
            x0 = x_mid

        error = abs(f_mid)
        it += 1

        # Guard against an infinite loop
        if it > max_it:
            print("Oops, iteration count is very large. Breaking out of while loop.")
            break

    return x_mid, f_mid, it

print("Scipy Method:")
%time r = optimize.bisect(my_f,0, 2)
print(r)
print("\nMy Method:")
%time compute_root(my_f, x0=0, x1=2, tol=1.0e-6, max_it=1000)[0]

Scipy Method:
CPU times: user 251 μs, sys: 281 μs, total: 532 μs
Wall time: 552 μs
1.1568354643623024

My Method:
CPU times: user 62 μs, sys: 1 μs, total: 63 μs
Wall time: 65.1 μs


1.1568354368209839

Both functions returned the same answer to the first 7 significant figures, after which point they diverge from one another. My function took significantly less time than scipy's did, taking about 70μs compared to 550μs.